### ISSUE TITLE
QuotaExceededError on localStorage.setItem()

### ISSUE THREAD

**Issue by danny7i** [ganlanyuan/tiny-slider#224] opened 2018-07-09 09:08 UTC
__Issue description__:  

Our Windows 10 users have been getting QuotaExceededError when localStorage.setItem() (in setLocalStorage.js) is called. 

This is probably due to their localStorage is full.

Is there anything tiny-slider can do to prevent this error? Possibly a try catch block around setItem()?

_Tiny-slider version_:   2.7.4
_Browser name && version_:  EDGE 17; IE11
_OS name && version_:   Windows 10

Thanks

**Comment by ganlanyuan** [comment] 2018-07-09 12:09
Please let me know how to reproduce this issue.
I just tested on IE11 and Edge14 with "private mode" and "Block all Cookies" and it works as expected.

**Comment by danny7i** [comment] 2018-07-10 10:04
@ganlanyuan I think it only happens if your localStorage is full (i.e. all 5MB quota was already used up and there is not more space allowed to save any more data in it)

**Comment by ganlanyuan** [comment] 2018-07-10 12:40
I see.
Should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/eb9da385d05201b5e1d4c3a41c07b41a7d24179f).

**Comment by ganlanyuan** [comment] 2018-07-11 19:01
Released in v2.8.1

**Comment by ganlanyuan** [comment] 2018-07-17 14:37
Feel free to reopen it if the issue still exist

**Closed by ganlanyuan** 2018-07-17 14:37 UTC
Labels: bug

**Comment by danny7i** [comment] 2018-10-23 09:42
@ganlanyuan This issue has re-appeared on our production site for several users on IE/Edge, using at least 2.8.5 of tiny-slider.

Stacktrace
![image](https://user-images.githubusercontent.com/1275768/47351485-f4d4ae80-d6af-11e8-90fb-41c7bdda093b.png)

This could be because of IE/Edge's erratic behaviours on local storage limitation, where if the user has hit a global limit across the browser, each website would not be able to use it. See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15339542/

Can I suggest a graceful fallback if the error is caught, just avoid using local storage for these users? I cannot re-open this issue so just leaving the comment here. Hope this gets your attention. 

Thanks!

**Comment by ganlanyuan** [comment] 2018-10-23 18:46
So do you think the error is caused by this row?
```js
if (access) { storage.setItem(key, value); }
```

**Comment by ganlanyuan** [comment] 2018-11-12 16:13
@danny7i This should be fixed in [this commit]
