### ISSUE TITLE
On mobile/touch - horizontal scrolling should be locked when page is scrolling vertically (and vice versa)

### ISSUE THREAD

**Issue by Defcon0** [ganlanyuan/tiny-slider#324] opened 2018-11-05 16:37 UTC
Hello,

inspired by https://github.com/kenwheeler/slick/issues/1543 where we had the same issue with slick slider.

When a swipe axis direction is detected, tinyslider should lock the other swipe axis direction, i.e. if I swipe horizontally, vertical swiping should be locked and vice versa.

Is there already an option for that I might've missed or is it a feature request?

Bye Defcon0

**Comment by seriouslysean** [comment] 2018-11-05 20:06
This is a duplicate of https://github.com/ganlanyuan/tiny-slider/issues/119 that has been open for a while. I suggest adding your info there instead and closing this one.

**Comment by Defcon0** [comment] 2018-11-05 20:17
No, I don’t think it’s the same problem. But thanks anyway for the hint.

**Comment by seriouslysean** [comment] 2018-11-05 20:50
Take a look at this comment, https://github.com/ganlanyuan/tiny-slider/issues/119#issuecomment-425356096. It sounds like the same issue you're describing (other than the fact you'd like it to work in both directions). I also posted a reproduction of the issue that was being experienced there, https://github.com/ganlanyuan/tiny-slider/issues/119#issuecomment-436027248 as I ran in to the same thing.

The issue described is saying when utilizing a slider, you're able to scroll on the X/Y axis while swiping through the slides which your suggestion here would fix. Whether it's a bug or a feature request at this point I'm not sure but these two issues feel like one solution would solve both things.

**Comment by Defcon0** [comment] 2018-11-05 22:09
Could be. If you don’t mind, I‘d be interested what the author @ganlanyuan thinks about the issue.

**Comment by seriouslysean** [comment] 2018-11-05 22:19
Yeah defnitely, I’m not trying to dissuade you. Just trying to figure out if it’s the same issue or not to help consolidate things.

**Comment by ganlanyuan** [comment] 2018-11-06 22:34
Thanks @seriouslysean 

@Defcon0 There is an option `swipeAngle` for this. 
```js
{
  swipeAngle: 15 // default: angle between swipe direction and the slider axis
}
```
This will prevent the slider from horizontal scrolling when you scroll the page.

**Comment by seriouslysean** [comment] 2018-11-07 17:19
@defcon0 this was actually added in the latest commit to tiny slider, https://github.com/ganlanyuan/tiny-slider/issues/162#issuecomment-436641388. You can use the new `preventScrollOnTouch’ option. See this commit, https://github.com/ganlanyuan/tiny-slider/commit/f0eb94a63e7cda9ab7831a45a191ce8e914deb21.

**Comment by ganlanyuan** [comment] 2018-11-08 22:21
2.8.8 is not published yet.

**Closed** 2018-11-11 10:46 UTC
