### ISSUE TITLE
lazyload issue: image didn't get loaded after 5 times of forward clicking

### ISSUE THREAD

**Issue by jechav** [ganlanyuan/tiny-slider#96] opened 2017-11-01 16:11 UTC
Click event for cloned elements is missing with 'loop:true'. 

Also with lazyload option there is a issue with loop:true, because is apply in cloned items and the validation doest work sometimes and the placeholder image is shown.

https://prnt.sc/h4vw20

**Comment by ganlanyuan** [comment] 2017-11-02 02:14
Hey @jechav ,
Could you make a demo? I'm not sure what the issue is.

**Comment by jechav** [comment] 2017-11-02 20:41
thanks to answer @ganlanyuan 
https://codesandbox.io/s/mqr949kvyx after of 5 times to forward doesnt update the real image, and lets the placeholder instead, in this case a grey image.

**Comment by ganlanyuan** [comment] 2017-11-05 21:27
This should be fixed in [v2.2.6](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.2.6)

**Comment by jechav** [comment] 2017-11-07 14:37
@ganlanyuan fixed thanks so much.

**Closed** 2017-11-07 15:06 UTC
Labels: bug
